In [154]:
# https://www.youtube.com/watch?v=eshMzk8L3ic
import pandas as pd


In [155]:
data = pd.read_csv('datasets/Traveler trip dataset/Travel details dataset.csv')
data.shape
#data.head() # to display first 5 values
#data.tail() # to display last 5 values.


(138, 14)

In [156]:
print("The number of rows :",data.shape[0])
print("The number of columns :",data.shape[1])

The number of rows : 138
The number of columns : 14


In [157]:
data.info()# to getv the stat of the data set.
data.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Trip ID               138 non-null    int64 
 1   Destination city      138 non-null    object
 2   Destination country   138 non-null    object
 3   Start date            138 non-null    object
 4   End date              138 non-null    object
 5   Duration (days)       138 non-null    int64 
 6   Traveler name         138 non-null    object
 7   Traveler age          138 non-null    int64 
 8   Traveler gender       138 non-null    object
 9   Traveler nationality  138 non-null    object
 10  Accommodation type    138 non-null    object
 11  Accommodation cost    138 non-null    object
 12  Transportation type   138 non-null    object
 13  Transportation cost   138 non-null    object
dtypes: int64(3), object(11)
memory usage: 15.2+ KB


Trip ID                 0
Destination city        0
Destination country     0
Start date              0
End date                0
Duration (days)         0
Traveler name           0
Traveler age            0
Traveler gender         0
Traveler nationality    0
Accommodation type      0
Accommodation cost      0
Transportation type     0
Transportation cost     0
dtype: int64

In [158]:
#data['Accommodation type'].unique()

data['Transportation type'].unique()
data['Destination city'].unique()

array(['London', 'Phuket', 'Bali', 'New York', 'Tokyo', 'Paris', 'Sydney',
       'Rio de Janeiro', 'Amsterdam', 'Dubai', 'Cancun', 'Barcelona',
       'Honolulu', 'Berlin', 'Marrakech', 'Edinburgh', 'Rome', 'Bangkok',
       'Hawaii', 'Japan', 'Thailand', 'France', 'Australia', 'Brazil',
       'Greece', 'Egypt', 'Mexico', 'Italy', 'Spain', 'Canada',
       'New York City', 'Vancouver', 'Seoul', 'Los Angeles', 'Cape Town',
       'Santorini', 'Phnom Penh', 'Athens', 'Auckland', 'kerala'],
      dtype=object)

In [159]:
data['Accommodation type']=data['Accommodation type'].map({'Hotel':0,'Resort':1,'Villa':2,'Airbnb':3,'Hostel':4,'Raid':5,'Vacation rental':6,'Guesthouse':7})
data
data['Transportation type']=data['Transportation type'].map({'Flight':0,'Train':1,'Plane':2,'Bus':3,'Car rental':4,'Subway':5,'Car':6,'Ferry':7,'Airplane':8})
data

Trip ID Destination city Destination country Start date   End date  \
0          1           London                  UK   5/1/2023   5/8/2023   
1          2           Phuket            Thailand  6/15/2023  6/20/2023   
2          3             Bali           Indonesia   7/1/2023   7/8/2023   
3          4         New York                 USA  8/15/2023  8/29/2023   
4          5            Tokyo               Japan  9/10/2023  9/17/2023   
..       ...              ...                 ...        ...        ...   
133      136        Vancouver              Canada  8/15/2023  8/21/2023   
134      137          Bangkok            Thailand   9/1/2023   9/8/2023   
135      138        Barcelona               Spain  9/15/2023  9/22/2023   
136      139         Auckland         New Zealand  10/1/2023  10/8/2023   
137      140           kerala               India  15/2/2023   1/3/2023   

     Duration (days)    Traveler name  Traveler age Traveler gender  \
0                  7       John Smith            35            Male   
1                  5         Jane Doe            28          Female   
2                  7        David Lee            45            Male   
3                 14    Sarah Johnson            29          Female   
4                  7       Kim Nguyen            26          Female   
..               ...              ...           ...             ...   
133                6      Emma Wilson            29          Female   
134                7        Ryan Chen            34            Male   
135                7  Sofia Rodriguez            25          Female   
136                7    William Brown            39            Male   
137               13      ryan ranold            50            male   

    Traveler nationality  Accommodation type Accommodation cost  \
0               American                 0.0               1200   
1               Canadian                 1.0                800   
2                 Korean                 2.0               1000   
3                British                 0.0               2000   
4             Vietnamese                 3.0                700   
..                   ...                 ...                ...   
133             Canadian                 0.0               5000   
134              Chinese                 4.0               2000   
135              Spanish                 3.0               6000   
136        New Zealander                 0.0               7000   
137                Korea                 0.0               1500   

     Transportation type Transportation cost  
0                      0                 600  
1                      0                 500  
2                      0                 700  
3                      0                1000  
4                      1                 200  
..                   ...                 ...  
133                    8                3000  
134                    1                1000  
135                    8                2500  
136                    1                2500  
137                    1                 750  

[138 rows x 14 columns]

In [160]:
X=data.drop(['Accommodation cost','Transportation cost'], axis=1)
y= data[['Accommodation cost','Transportation cost']]

In [161]:

data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Trip ID               138 non-null    int64  
 1   Destination city      138 non-null    object 
 2   Destination country   138 non-null    object 
 3   Start date            138 non-null    object 
 4   End date              138 non-null    object 
 5   Duration (days)       138 non-null    int64  
 6   Traveler name         138 non-null    object 
 7   Traveler age          138 non-null    int64  
 8   Traveler gender       138 non-null    object 
 9   Traveler nationality  138 non-null    object 
 10  Accommodation type    137 non-null    float64
 11  Accommodation cost    138 non-null    object 
 12  Transportation type   138 non-null    int64  
 13  Transportation cost   138 non-null    object 
dtypes: float64(1), int64(4), object(9)
memory usage: 15.2+ KB


In [162]:
data['Destination city'].unique()

array(['London', 'Phuket', 'Bali', 'New York', 'Tokyo', 'Paris', 'Sydney',
       'Rio de Janeiro', 'Amsterdam', 'Dubai', 'Cancun', 'Barcelona',
       'Honolulu', 'Berlin', 'Marrakech', 'Edinburgh', 'Rome', 'Bangkok',
       'Hawaii', 'Japan', 'Thailand', 'France', 'Australia', 'Brazil',
       'Greece', 'Egypt', 'Mexico', 'Italy', 'Spain', 'Canada',
       'New York City', 'Vancouver', 'Seoul', 'Los Angeles', 'Cape Town',
       'Santorini', 'Phnom Penh', 'Athens', 'Auckland', 'kerala'],
      dtype=object)

In [163]:
data['Destination country'].unique()

array(['UK', 'Thailand', 'Indonesia', 'USA', 'Japan', 'France',
       'Australia', 'Brazil', 'Netherlands', 'United Arab Emirates',
       'Mexico', 'Spain', 'Hawaii', 'Germany', 'morocco', 'Scotland',
       'Ubud', 'japan', 'Italy', 'US', 'Greece', 'Egypt', 'Canada', 'AUS',
       'South Korea', 'Jambodia', 'Barcelona', 'Indonasia', 'SA', 'Aus',
       'Thai', 'UAE', 'China', 'Rio', 'Africa', 'Uk', 'Ukraine',
       'cambodia', 'South Africa', 'New Zealand', 'India'], dtype=object)

In [164]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
ohe=OneHotEncoder()
cc_array=ohe.fit_transform(data[["Destination city"]]).toarray()
print(cc_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [165]:
cc_label=ohe.categories_
print(cc_label)

[array(['Amsterdam', 'Athens', 'Auckland', 'Australia', 'Bali', 'Bangkok',
       'Barcelona', 'Berlin', 'Brazil', 'Canada', 'Cancun', 'Cape Town',
       'Dubai', 'Edinburgh', 'Egypt', 'France', 'Greece', 'Hawaii',
       'Honolulu', 'Italy', 'Japan', 'London', 'Los Angeles', 'Marrakech',
       'Mexico', 'New York', 'New York City', 'Paris', 'Phnom Penh',
       'Phuket', 'Rio de Janeiro', 'Rome', 'Santorini', 'Seoul', 'Spain',
       'Sydney', 'Thailand', 'Tokyo', 'Vancouver', 'kerala'], dtype=object)]


In [166]:
new_cc_label=np.array(cc_label).ravel()

In [167]:
city=pd.DataFrame(cc_array, columns = new_cc_label)
print(city)

     Amsterdam  Athens  Auckland  Australia  Bali  Bangkok  Barcelona  Berlin  \
0          0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   
1          0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   
2          0.0     0.0       0.0        0.0   1.0      0.0        0.0     0.0   
3          0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   
4          0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   
..         ...     ...       ...        ...   ...      ...        ...     ...   
133        0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   
134        0.0     0.0       0.0        0.0   0.0      1.0        0.0     0.0   
135        0.0     0.0       0.0        0.0   0.0      0.0        1.0     0.0   
136        0.0     0.0       1.0        0.0   0.0      0.0        0.0     0.0   
137        0.0     0.0       0.0        0.0   0.0      0.0        0.0     0.0   

     Brazil  Canada  ...  R

In [168]:
new_data= pd.concat([data,city], axis=1)
print(new_data)

     Trip ID Destination city Destination country Start date   End date  \
0          1           London                  UK   5/1/2023   5/8/2023   
1          2           Phuket            Thailand  6/15/2023  6/20/2023   
2          3             Bali           Indonesia   7/1/2023   7/8/2023   
3          4         New York                 USA  8/15/2023  8/29/2023   
4          5            Tokyo               Japan  9/10/2023  9/17/2023   
..       ...              ...                 ...        ...        ...   
133      136        Vancouver              Canada  8/15/2023  8/21/2023   
134      137          Bangkok            Thailand   9/1/2023   9/8/2023   
135      138        Barcelona               Spain  9/15/2023  9/22/2023   
136      139         Auckland         New Zealand  10/1/2023  10/8/2023   
137      140           kerala               India  15/2/2023   1/3/2023   

     Duration (days)    Traveler name  Traveler age Traveler gender  \
0                  7       J

In [169]:
Dc_array=ohe.fit_transform(data[['Destination country']]).toarray()
print(Dc_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [170]:
Dc_label=ohe.categories_
print(Dc_label)

[array(['AUS', 'Africa', 'Aus', 'Australia', 'Barcelona', 'Brazil',
       'Canada', 'China', 'Egypt', 'France', 'Germany', 'Greece',
       'Hawaii', 'India', 'Indonasia', 'Indonesia', 'Italy', 'Jambodia',
       'Japan', 'Mexico', 'Netherlands', 'New Zealand', 'Rio', 'SA',
       'Scotland', 'South Africa', 'South Korea', 'Spain', 'Thai',
       'Thailand', 'UAE', 'UK', 'US', 'USA', 'Ubud', 'Uk', 'Ukraine',
       'United Arab Emirates', 'cambodia', 'japan', 'morocco'],
      dtype=object)]


In [171]:
Dcc_label=np.array(Dc_label).ravel()
print(Dcc_label)

['AUS' 'Africa' 'Aus' 'Australia' 'Barcelona' 'Brazil' 'Canada' 'China'
 'Egypt' 'France' 'Germany' 'Greece' 'Hawaii' 'India' 'Indonasia'
 'Indonesia' 'Italy' 'Jambodia' 'Japan' 'Mexico' 'Netherlands'
 'New Zealand' 'Rio' 'SA' 'Scotland' 'South Africa' 'South Korea' 'Spain'
 'Thai' 'Thailand' 'UAE' 'UK' 'US' 'USA' 'Ubud' 'Uk' 'Ukraine'
 'United Arab Emirates' 'cambodia' 'japan' 'morocco']


In [172]:
new_country = pd.DataFrame(Dc_array,columns=Dcc_label)
print(new_country)

     AUS  Africa  Aus  Australia  Barcelona  Brazil  Canada  China  Egypt  \
0    0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
1    0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
2    0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
3    0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
4    0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
..   ...     ...  ...        ...        ...     ...     ...    ...    ...   
133  0.0     0.0  0.0        0.0        0.0     0.0     1.0    0.0    0.0   
134  0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
135  0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
136  0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   
137  0.0     0.0  0.0        0.0        0.0     0.0     0.0    0.0    0.0   

     France  ...   UK   US  USA  Ubud   Uk  Ukraine  United Arab Emirates  

In [176]:
new_data1=pd.concat([new_data,new_country], axis=1)
data=new_data1
print(data)

     Trip ID Destination city Destination country Start date   End date  \
0          1           London                  UK   5/1/2023   5/8/2023   
1          2           Phuket            Thailand  6/15/2023  6/20/2023   
2          3             Bali           Indonesia   7/1/2023   7/8/2023   
3          4         New York                 USA  8/15/2023  8/29/2023   
4          5            Tokyo               Japan  9/10/2023  9/17/2023   
..       ...              ...                 ...        ...        ...   
133      136        Vancouver              Canada  8/15/2023  8/21/2023   
134      137          Bangkok            Thailand   9/1/2023   9/8/2023   
135      138        Barcelona               Spain  9/15/2023  9/22/2023   
136      139         Auckland         New Zealand  10/1/2023  10/8/2023   
137      140           kerala               India  15/2/2023   1/3/2023   

     Duration (days)    Traveler name  Traveler age Traveler gender  \
0                  7       J